# Generated by Django 2.1.1 on 2018-10-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181018_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='procore_status',
            field=models.NullBooleanField(),
        ),
    ]
