# Generated by Django 2.1.1 on 2018-10-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prior_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('disability', models.CharField(blank=True, max_length=255, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('smoker', models.CharField(blank=True, max_length=255, null=True)),
                ('veteran', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_status_effective_date', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_status', models.CharField(blank=True, max_length=255, null=True)),
                ('hire_date', models.CharField(blank=True, max_length=255, null=True)),
                ('rehire_date', models.CharField(blank=True, max_length=255, null=True)),
                ('termination_date', models.CharField(blank=True, max_length=255, null=True)),
                ('user_account_deactivation_date', models.CharField(blank=True, max_length=255, null=True)),
                ('annual_salary', models.FloatField(blank=True, null=True)),
                ('cost_code', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('eeo_class', models.FloatField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_supervisor_reviewer', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employee_master',
                'managed': True,
            },
        ),
    ]
