from django.db import models
from datetime import datetime


class Project(models.Model):

    procore_index = models.FloatField(null=True,blank=True)
    pjm_index = models.DecimalField(max_digits=28,null=True,blank=True,decimal_places=10)
    system_of_origin = models.CharField(max_length=7)
    project = models.CharField(max_length=53)
    project_number = models.CharField(max_length=15,null=True,blank=True)
    project_description = models.CharField(max_length=35,null=True,blank=True)
    address = models.CharField(max_length=71,null=True,blank=True)
    city = models.CharField(max_length=35,null=True,blank=True)
    state = models.CharField(max_length=9,null=True,blank=True)
    zip = models.CharField(max_length=15,null=True,blank=True)
    latitude = models.FloatField(null=True,blank=True)
    longitude = models.FloatField(null=True,blank=True)
    project_stage = models.CharField(max_length=255,null=True,blank=True)
    phone = models.CharField(max_length=20,null=True,blank=True)
    created = models.CharField(max_length=255,null=True,blank=True)
    last_updated = models.CharField(max_length=255,null=True,blank=True)
    procore_status = models.NullBooleanField()
    sage_status = models.CharField(max_length=25,null=True,blank=True)
    project_status = models.CharField(max_length=8) 
    Construction_Type = models.CharField(max_length=20,null=True,blank=True)
    product_type = models.CharField(max_length=20,null=True,blank=True)
    size = models.BigIntegerField(null=True,blank=True)
    estimated_start = models.DateTimeField(default=None,null=True)
    revised_start = models.DateTimeField(default=None,null=True)
    actual_start = models.DateTimeField(default=None,null=True)
    estimated_completion = models.DateTimeField(default=None,null=True)
    revised_completion = models.DateTimeField(default=None,null=True)
    actual_completion = models.DateTimeField(default=None,null=True)
    customer_id = models.CharField(max_length=15,null=True,blank=True)
    customer_name = models.CharField(max_length=55,null=True,blank=True)
    architect = models.CharField(max_length=255,null=True,blank=True)
    division = models.CharField(max_length=22,null=True,blank=True)
    contract_type = models.CharField(max_length=255,null=True,blank=True)
    team_leader = models.CharField(max_length=255,null=True,blank=True)
    project_managers = models.CharField(max_length=255,null=True,blank=True)
    superintendents = models.CharField(max_length=255,null=True,blank=True)
    original_contract_value = models.FloatField(null=True,blank=True)
    approved_contract_changes =  models.FloatField(null=True,blank=True)
    revised_contract_value = models.FloatField(null=True,blank=True)
    jtd_work_billed = models.FloatField(null=True,blank=True)
    jtd_retainage_held = models.FloatField(null=True,blank=True)
    jtd_payments_received = models.FloatField(null=True,blank=True)
    original_estimated_cost = models.FloatField(null=True,blank=True)
    approved_estimate_changes = models.FloatField(null=True,blank=True)
    revised_estimated_cost = models.FloatField(null=True,blank=True)
    original_committed_cost = models.FloatField(null=True,blank=True)
    approved_commitment_changes = models.FloatField(null=True,blank=True)
    revised_committed_cost = models.FloatField(null=True,blank=True)
    jtd_cost = models.FloatField(null=True,blank=True)
    jtd_payments_made = models.FloatField(null=True,blank=True)
    projected_post = models.FloatField(null=True,blank=True)
    original_gp = models.FloatField(null=True,blank=True)
    projected_gp = models.DecimalField(max_digits=28,null=True,blank=True,decimal_places=10)
    original_gp_percent = models.FloatField(null=True,blank=True)
    projected_gp_percent = models.FloatField(null=True,blank=True)
    gain_fade = models.FloatField(null=True,blank=True)
    gain_fade_percent = models.FloatField(null=True,blank=True)
    database_stamp = models.CharField(max_length=4)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = True
        db_table = 'project_master'

